### ISSUE TITLE
KCT warning bug

### ISSUE THREAD

**Issue by NightShift10125** [severedsolo/Bureaucracy#18] opened 2021-09-16 22:55 UTC
The KCT warning is still showing up for me even with it being set to false, unsure what causes the bug.

Also I would like to request support for the Strategia mod, the mod adds strategies that changes the globe science value however Bureaucracy keeps the value based of the game settings.
Strategia also has strategies that effect which level fresh crew start at which Bureaucracy overrides as well.

link to Strategia here:
https://github.com/jrossignol/Strategia

**Comment by severedsolo** [comment] 2021-09-17 05:58
On the KCT thing - have you updated? 1.5 should detect your KCT settings and manage it by itself, ShowKCTWarning is deprecated. (1.5 is KSP 1.12+ and doesn't work on older versions, but I only support the latest version of the game).

Strategia I will take a look into.

**Comment by NightShift10125** [comment] 2021-09-17 17:17
I'm using the 1.5.1 version from CKAN (however according to the 'defaultsettings' CFG file it's version 1.4.0.1) with the latest version of KSP with the 'ShowKCTWarning' set to false yet I still get the warning.
I might have to do with the fact I'm using JNSQ but I am unsure of it.
Also I'm not sure if this is intended or not but for me when I reinstall the mod the 'defaultsettings' CFG file doesn't appear until I boot the game up once

**Comment by severedsolo** [comment] 2021-09-17 17:32
Don't worry about the settings version file - I only update the version when I actually make changes to the settings, that's the latest.

ShowKCTWarning doesn't do anything any more - the mod detects your KCT settings, and warns you if it finds a problem (ie you have KCT facility handling turned on, and Bureaucracys facility handling turned on). If you are *absolutely sure* this is not the case, then I'll need to see your BureaucracySettings.cfg file (from your save folder) and your KCT_Settings.cfg (also from your save folder) to see if I can reproduce.

And yes, defaultSettings.cfg generates itself if it can't be found, rather than shipping with the dll to stop CKAN from overwriting your settings.

**Comment by NightShift10125** [comment] 2021-09-17 19:29
Here is the files you wanted, had to put them in a zipped file to share through GitHub.

[Bureaucracy and KCT bugged file.zip](https://github.com/severedsolo/Bureaucracy/files/7188076/Bureaucracy.and.KCT.bugged.file.zip)

**Comment by severedsolo** [comment] 2021-09-17 20:38
Yup, working as intended. Your KCT preset is showing KSCUpgradeTimes = True and your BureaucracySettings file is showing HandleKSCUpgrades = True - only one of those should be true. You need to decide which mod you want to let handle your facility upgrades.

**Comment by severedsolo** [comment] 2021-09-18 05:54
To keep the issue tracker clean, I've raised a separate issue for Strategia support, closing this one as working as intended.

**Closed as completed by severedsolo** 2021-09-18 05:54 UTC
Labels: Not a bug
